Models/Pokemones.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PokedexMalHecho.Models
{
    public partial class Pokemones
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Campo Requerido")]
        [StringLength(50)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public int Tipo1 { get; set; }
        public int? Tipo2 { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public int Region { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [StringLength(50)]
        public string Ataque1 { get; set; }
        [StringLength(50)]
        public string Ataque2 { get; set; }
        [StringLength(50)]
        public string Ataque3 { get; set; }
        [StringLength(50)]
        public string Ataque4 { get; set; }
        [StringLength(100)]
        public string Photo { get; set; }

        public virtual Regiones RegionNavigation { get; set; }
        public virtual Tipos Tipo1Navigation { get; set; }
        public virtual Tipos Tipo2Navigation { get; set; }
    }
}

Controllers/PokemonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PokedexMalHecho.Models;
using PokedexMalHecho.DTO;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using AutoMapper;
using Microsoft.Extensions.FileProviders;

namespace PokedexMalHecho.Controllers
{
    public class PokemonesController : Controller
    {
        private readonly PokedexMalHechoContext _context;
        private readonly IHostingEnvironment hostingEnvironment;
        //private readonly IMapper _mapper;

        public PokemonesController(PokedexMalHechoContext context, IHostingEnvironment hostingEnvironment/*, IMapper mapper*/)
        {
            _context = context;
            this.hostingEnvironment = hostingEnvironment;
            //this._mapper = mapper;
        }

        // GET: Pokemones
        public async Task<IActionResult> Index(/*string nombrePokemon = null*/)
        {
            /*var pokemonList = _context.Pokemones.AsQueryable();
            if (!string.IsNullOrEmpty(nombrePokemon))
            {
                pokemonList = _context.Pokemones.Where(x => x.Nombre.Contains(nombrePokemon));
            }
            var list = await pokemonList.ToListAsync();
            return View(list);*/

            var pokedexMalHechoContext = _context.Pokemones.Include(p => p.RegionNavigation).Include(p => p.Tipo1Navigation).Include(p => p.Tipo2Navigation);
            return View(await pokedexMalHechoContext.ToListAsync());
        }

        // GET: Pokemones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pokemones = await _context.Pokemones
                .Include(p => p.RegionNavigation)
                .Include(p => p.Tipo1Navigation)
                .Include(p => p.Tipo2Navigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pokemones == null)
            {
                return NotFound();
            }

            return View(pokemones);
        }

        // GET: Pokemones/Create
        public IActionResult Create()
        {
            ViewData["Region"] = new SelectList(_context.Regiones, "Id", "Nombre");
            ViewData["Tipo1"] = new SelectList(_context.Tipos, "Id", "Nombre");
            ViewData["Tipo2"] = new SelectList(_context.Tipos, "Id", "Nombre");
            return View();
        }

        // POST: Pokemones/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Tipo1,Tipo2,Region,Ataque1,Ataque2,Ataque3,Ataque4,Photo")] PokemonesDTO DTO)
        //public async Task<IActionResult> Create(PokemonesDTO DTO)
        //public IActionResult Create(PokemonesDTO DTO)
        {
            //var pokemon = new Pokemones();
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if(DTO.Photo != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + DTO.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    DTO.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                    //if (filePath != null) DTO.Photo.CopyTo(new FileStream(filePath, mode: FileMode.Create));
                }

                //pokemon = _mapper.Map<Pokemones>(DTO);
                //pokemon.Photo = uniqueFileName;
                Pokemones newPokemon = new Pokemones
                {
                    Id = DTO.Id,
                    Nombre = DTO.Nombre,
                    Tipo1 = DTO.Tipo1,
                    Tipo2 = DTO.Tipo2,
                    Region = DTO.Region,
                    Ataque1=DTO.Ataque1,
                    Ataque2=DTO.Ataque2,
                    Ataque3=DTO.Ataque3,
                    Ataque4=DTO.Ataque4,
                    Photo=uniqueFileName
                };
                _context.Add(newPokemon);
                await _context.SaveChangesAsync();
                return RedirectToAction(/*nameof(Index)*/ "index",new { id = newPokemon.Id});
            }
            /*ViewData["Region"] = new SelectList(_context.Regiones, "Id", "Nombre", pokemones.Region);
            ViewData["Tipo1"] = new SelectList(_context.Tipos, "Id", "Nombre", pokemones.Tipo1);
            ViewData["Tipo2"] = new SelectList(_context.Tipos, "Id", "Nombre", pokemones.Tipo2);*/
            return View(/*DTOpokemones*/);
        }

        // GET: Pokemones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var pokemones = await _context.Pokemones.FindAsync(id);
            if (pokemones == null)
            {
                return NotFound();
            }
            ViewData["Region"] = new SelectList(_context.Regiones, "Id", "Nombre", pokemones.Region);
            ViewData["Tipo1"] = new SelectList(_context.Tipos, "Id", "Nombre", pokemones.Tipo1);
            ViewData["Tipo2"] = new SelectList(_context.Tipos, "Id", "Nombre", pokemones.Tipo2);

            var pokemonesDTO = new PokemonesDTO()
            {
                Id = pokemones.Id,
                Nombre = pokemones.Nombre,
                Region = pokemones.Region,
                Tipo1 = pokemones.Tipo1,
                Tipo2 = pokemones.Tipo2,
                Ataque1 = pokemones.Ataque1,
                Ataque2 = pokemones.Ataque2,
                Ataque3 = pokemones.Ataque3,
                Ataque4 = pokemones.Ataque4
                //Photo=pokemones.Photo
            };

            return View(pokemonesDTO);
        }

        // POST: Pokemones/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Tipo1,Tipo2,Region,Ataque1,Ataque2,Ataque3,Ataque4,Photo")] /*Pokemones pokemones*/ PokemonesDTO dTO)
        {
            if (id != dTO.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var pokemon = await _context.Pokemones.FirstOrDefaultAsync(d => d.Id == dTO.Id);

                    string uniqueName = null;
                    if (dTO.Photo != null)
                    {
                        string folderPath = Path.Combine(hostingEnvironment.WebRootPath, "images");
                        uniqueName = Guid.NewGuid().ToString() + "_" + dTO.Photo.FileName;
                        string filePath = Path.Combine(folderPath, uniqueName);

                        string filePathDelete = Path.Combine(folderPath, pokemon.Photo);

                        if (!string.IsNullOrEmpty(pokemon.Photo))
                        {
                            if (System.IO.File.Exists(filePathDelete))
                            {
                                var fileInfo = new System.IO.FileInfo(filePathDelete);
                                fileInfo.Delete();
                            }
                        }
                        if (filePath != null) dTO.Photo.CopyTo(new FileStream(filePath, mode: FileMode.Create));
                    }
                    pokemon.Id = dTO.Id;
                    pokemon.Region = dTO.Region;
                    pokemon.Tipo1 = dTO.Tipo1;
                    pokemon.Tipo2 = dTO.Tipo2;
                    pokemon.Ataque1 = dTO.Ataque1;
                    pokemon.Ataque2 = dTO.Ataque2;
                    pokemon.Ataque3 = dTO.Ataque3;
                    pokemon.Ataque4 = dTO.Ataque4;
                    pokemon.Photo = uniqueName;

                    _context.Update(pokemon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PokemonesExists(dTO.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dTO);

            /*
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pokemones);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PokemonesExists(pokemones.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Region"] = new SelectList(_context.Regiones, "Id", "Nombre", pokemones.Region);
            ViewData["Tipo1"] = new SelectList(_context.Tipos, "Id", "Nombre", pokemones.Tipo1);
            ViewData["Tipo2"] = new SelectList(_context.Tipos, "Id", "Nombre", pokemones.Tipo2);
            return View(pokemones);*/
        }

        // GET: Pokemones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pokemones = await _context.Pokemones
                .Include(p => p.RegionNavigation)
                .Include(p => p.Tipo1Navigation)
                .Include(p => p.Tipo2Navigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pokemones == null)
            {

Views/Pokemones/Create.cshtml
@model PokedexMalHecho.DTO.PokemonesDTO

@{
    ViewData["Title"] = "Creación Pokemon";
}

<h1>Creación Pokemon</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre:</label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col">
                    <label asp-for="Tipo1" class="control-label">Tipo 1:</label>
                    <select asp-for="Tipo1" class="form-control" asp-items="ViewBag.Tipo1">
                        <option>Seleccionar Tipo</option>
                    </select>
                </div>
                <div class="col">
                    <label asp-for="Tipo2" class="control-label">Tipo 2:</label>
                    <select asp-for="Tipo2" class="form-control" asp-items="ViewBag.Tipo2">
                        <option>Seleccionar Tipo</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Region" class="control-label">Región:</label>
                <select asp-for="Region" class="form-control" asp-items="ViewBag.Region">
                    <option>Seleccionar Región</option>
                </select>
            </div>

            <div class="row">
                <div class="col">
                    <label asp-for="Ataque1" class="control-label">Ataque 1:</label>
                    <input asp-for="Ataque1" class="form-control" />
                    <span asp-validation-for="Ataque1" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="Ataque2" class="control-label">Ataque 2:</label>
                    <input asp-for="Ataque2" class="form-control" />
                    <span asp-validation-for="Ataque2" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <label asp-for="Ataque3" class="control-label">Ataque 3:</label>
                    <input asp-for="Ataque3" class="form-control" />
                    <span asp-validation-for="Ataque3" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="Ataque4" class="control-label">Ataque 4:</label>
                    <input asp-for="Ataque4" class="form-control" />
                    <span asp-validation-for="Ataque4" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Photo" class="control-label">Archivo Foto:</label>
                <div class="col">
                    <div class="custom-file">
                        <input asp-for="Photo" class="form-control custom-file-input" />
                        <label class="custom-file-label">Escoger archivo</label>
                    </div>
                </div>
            </div>

            <div class="row" style="margin-top:20px">
                <div class="col">
                    <input type="submit" value="Crear" class="btn btn-primary" /> |
                    <a asp-action="Index">Volver a Listado</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pokemones/Delete.cshtml
@model PokedexMalHecho.Models.Pokemones

@{
    ViewData["Title"] = "Eliminación Pokemon";
}

<h1>Eliminación Pokemon</h1>
<h3>¿Esta seguro que quiere eliminar este pokemon?</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt class="col-sm-2">
            Región
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegionNavigation.Nombre)
        </dd>
        <dt class="col-sm-2">
            Tipo 1
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo1Navigation.Nombre)
        </dd>
        <dt class="col-sm-2">
            Tipo 2
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo2Navigation.Nombre)
        </dd>
        <dt class="col-sm-2">
            Ataque 1
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ataque1)
        </dd>
        <dt class="col-sm-2">
           Ataque 2
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ataque2)
        </dd>
        <dt class="col-sm-2">
            Ataque 3
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ataque3)
        </dd>
        <dt class="col-sm-2">
            Ataque 4
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ataque4)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a Listado</a>
    </form>
</div>

Views/Pokemones/Details.cshtml
@model PokedexMalHecho.Models.Pokemones

@{
    ViewData["Title"] = "Detalles";
    var photoPath = "~/images/" + (Model.Photo ?? "noimage.jpg");
}

<h1>Detalles</h1>

<div>
    <hr />
</div>

<div class="card mb-3" sytle="max-width:540px">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="@photoPath" asp-append-version="true" class="card-img" alt=""/>
        </div>

        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayFor(model => model.Nombre)</h5>
                <p class="card-text">Región: @Html.DisplayFor(model => model.RegionNavigation.Nombre)</p>
                <p class="card-text">Tipos: @Html.DisplayFor(model => model.Tipo1Navigation.Nombre) y @Html.DisplayFor(model => model.Tipo2Navigation.Nombre)</p>
                <p class="card-text">Atáques: @Html.DisplayFor(model => model.Ataque1), @Html.DisplayFor(model => model.Ataque2), @Html.DisplayFor(model => model.Ataque3), @Html.DisplayFor(model => model.Ataque4)</p>
                <p class="card-text"></p>
            </div>
        </div>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Volver a Listado</a>
</div>

Views/Pokemones/Edit.cshtml
@model PokedexMalHecho.DTO.PokemonesDTO

@{
    ViewData["Title"] = "Edición Pokemon";
}

<h1>Editar Pokemon</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre:</label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col">
                    <label asp-for="Tipo1" class="control-label">Tipo 1:</label>
                    <select asp-for="Tipo1" class="form-control" asp-items="ViewBag.Tipo1"></select>
                    <span asp-validation-for="Tipo1" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="Tipo2" class="control-label">Tipo 2:</label>
                    <select asp-for="Tipo2" class="form-control" asp-items="ViewBag.Tipo2"></select>
                    <span asp-validation-for="Tipo2" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Region" class="control-label">Región</label>
                <select asp-for="Region" class="form-control" asp-items="ViewBag.Region"></select>
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col">
                    <label asp-for="Ataque1" class="control-label">Ataque 1:</label>
                    <input asp-for="Ataque1" class="form-control" />
                    <span asp-validation-for="Ataque1" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="Ataque2" class="control-label">Ataque 2:</label>
                    <input asp-for="Ataque2" class="form-control" />
                    <span asp-validation-for="Ataque2" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <label asp-for="Ataque3" class="control-label">Ataque 3:</label>
                    <input asp-for="Ataque3" class="form-control" />
                    <span asp-validation-for="Ataque3" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="Ataque4" class="control-label">Ataque 4:</label>
                    <input asp-for="Ataque4" class="form-control" />
                    <span asp-validation-for="Ataque4" class="text-danger"></span>
                </div>
            </div>

            <div class="col">
                <label asp-for="Photo" class="control-label">Archivo Foto:</label>
                
                <div class="custom-file">
                    <input asp-for="Photo" class="custom-file-input" id="=customFile"/>
                    <label asp-for="Photo" class="custom-file-label" for="customFile">Escoger archivo</label>
                </div>

            </div>

            <div class="row" style="margin-top:20px">
                <div class="col">
                    <input type="submit" value="Guardar" class="btn btn-primary" /> |
                    <a asp-action="Index">Volver a Listado</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pokemones/Index.cshtml
@model IEnumerable<PokedexMalHecho.Models.Pokemones>

@{
    ViewData["Title"] = "Listado Pokemones";
}

<h1>Listado Pokemones</h1>

<p>
    <a href="@Url.Action("Create","Pokemones")" class="btn btn-primary">Crear Pokemon</a>
</p>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                Región
            </th>
            <th>
                Tipo 1
            </th>
            <th>
                Tipo 2
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr bgcolor="@item.RegionNavigation.CodigoRga">
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.RegionNavigation.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo1Navigation.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo2Navigation.Nombre)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>